2024-02-01 15:35:40 | INFO | model_worker | args: Namespace(host='localhost', port=31021, worker_address='http://localhost:31021', controller_address='http://localhost:21001', model_path='/data/qiaoshuofei/PLMs/13b-chat', revision='main', device='cuda', gpus=None, num_gpus=2, max_gpu_memory='31Gib', dtype='float16', load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=['llama-2-13b-chat', 'text-embedding-ada-002'], conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-02-01 15:35:40 | INFO | model_worker | Loading the model ['llama-2-13b-chat', 'text-embedding-ada-002'] on worker bccda162 ...
2024-02-01 15:35:40 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                 | 0/3 [00:00<?, ?it/s]
2024-02-01 15:37:32 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                                                 | 0/3 [01:51<?, ?it/s]
2024-02-01 15:37:32 | ERROR | stderr | 
2024-02-01 15:37:32 | ERROR | stderr | Traceback (most recent call last):
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-02-01 15:37:32 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/runpy.py", line 87, in _run_code
2024-02-01 15:37:32 | ERROR | stderr |     exec(code, run_globals)
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 375, in <module>
2024-02-01 15:37:32 | ERROR | stderr |     args, worker = create_model_worker()
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 346, in create_model_worker
2024-02-01 15:37:32 | ERROR | stderr |     worker = ModelWorker(
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-01 15:37:32 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 348, in load_model
2024-02-01 15:37:32 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 95, in load_model
2024-02-01 15:37:32 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
2024-02-01 15:37:32 | ERROR | stderr |     return model_class.from_pretrained(
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
2024-02-01 15:37:32 | ERROR | stderr |     ) = cls._load_pretrained_model(
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model
2024-02-01 15:37:32 | ERROR | stderr |     state_dict = load_state_dict(shard_file)
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict
2024-02-01 15:37:32 | ERROR | stderr |     return torch.load(checkpoint_file, map_location=map_location)
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
2024-02-01 15:37:32 | ERROR | stderr |     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
2024-02-01 15:37:32 | ERROR | stderr |     result = unpickler.load()
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
2024-02-01 15:37:32 | ERROR | stderr |     typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
2024-02-01 15:37:32 | ERROR | stderr |   File "/root/anaconda3/envs/langchain/lib/python3.9/site-packages/torch/serialization.py", line 1112, in load_tensor
2024-02-01 15:37:32 | ERROR | stderr |     storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
2024-02-01 15:37:32 | ERROR | stderr | KeyboardInterrupt
